apiVersion: v1
kind: Pod
metadata:
  name: clogger
spec:
  containers:
  - name: clogger
    image: clogger:latest
    imagePullPolicy: Never
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
