apiVersion: apps/v1
kind: Deployment
metadata:
  name: clogger
  labels:
    app: clogger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clogger
  template:
    metadata:
      labels:
        app: clogger
    spec:
      containers:
      - name: clogger
        image: clogger:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"